# Generated by Django 5.0.7 on 2024-07-29 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campingplatz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buchung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('storniert', 'Storniert'), ('ohne_berechnung', 'Ohne Berechnung'), ('abgerechnet', 'Abgerechnet'), ('gutschreiben', 'Gutschreiben'), ('gutgeschrieben', 'Gutgeschrieben')], default='offen', max_length=20)),
                ('abrechnungsstatus', models.CharField(choices=[('offen', 'Offen'), ('storniert', 'Storniert'), ('ohne_berechnung', 'Ohne Berechnung'), ('abgerechnet', 'Abgerechnet'), ('gutschreiben', 'Gutschreiben'), ('gutgeschrieben', 'Gutgeschrieben')], default='offen', max_length=20)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campingplatz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campingplatz.campingplatz')),
            ],
        ),
    ]
