# Generated by Django 5.0.7 on 2024-08-03 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buchung', '0004_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
