# Generated by Django 5.0.7 on 2024-07-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campingplatz', '0002_rename_custumer_number_campingplatz_customer_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campingplatz',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
