# Generated by Django 5.0.7 on 2024-08-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchung', '0002_changelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='buchung',
            name='total_commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
