# Generated by Django 5.0.7 on 2024-07-29 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campingplatz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campingplatz',
            old_name='custumer_number',
            new_name='customer_number',
        ),
    ]
